name: dreidel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11.0
  - pip
  - conda-build
  - opencv
  - ipykernel
  - pydantic
  - omegaconf
  - gdown
  - codecov
  - pytest
  - matplotlib
  - black
  - scikit-learn
  - scipy
